
services:
  product-service:
    image: product-service:latest
    ports:
      - "8181:8181"
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

  elasticsearch:
    image: elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
